name: CI
on: [push]
jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare leiningen
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          lein: 2.9.5
      - name: Run all tests for all Clojure versions
        run: lein test-all
        shell: bash
